version: '3'

services:
 db:
   container_name: techinbrs-postgres
   ports:
     - 54322:5432
   environment:
     - POSTGRES_USER=${DB_USER}
     - POSTGRES_PASSWORD=${DB_PASS}
   image: postgres:14.4
   restart: unless-stopped

 pgadmin:
  container_name: techinbrs-pgadmin
  image: dpage/pgadmin4:latest
  ports:
    - 4433:443
    - 8080:80
  environment:
    - PGADMIN_DEFAULT_EMAIL=${PG_EMAIL}
    - PGADMIN_DEFAULT_PASSWORD=${PG_PASS}
  restart: unless-stopped
 strapi:
  container_name: techinbrs-strapi
  image: naskio/strapi:latest
  ports:
    - 1337:1337
  environment:
    - DATABASE_CLIENT=${STP_CLI}
    - DATABASE_HOST=${STP_HOST}
    - DATABASE_PORT=${STP_PORT}
    - DATABASE_NAME=${STP_NAME}
    - DATABASE_USERNAME=${STP_USER}
    - DATABASE_PASSWORD=${STP_PASS}
  restart: unless-stopped