version: '3'

services:
 db:
   container_name: techinbrs-postgres
   ports:
     - 54322:5432
   environment:
     - POSTGRES_USER=techinbrs
     - POSTGRES_PASSWORD=0632475779
   image: postgres:14.4
   restart: unless-stopped

 pgadmin:
  container_name: techinbrs-pgadmin
  image: dpage/pgadmin4:latest
  ports:
    - 4433:443
    - 8080:80
  environment:
    - PGADMIN_DEFAULT_EMAIL=techin-p@rmutp.ac.th
    - PGADMIN_DEFAULT_PASSWORD=0632475779
  restart: unless-stopped
 strapi:
  container_name: techinbrs-strapi
  image: naskio/strapi:latest
  ports:
    - 1337:1337
  environment:
    - DATABASE_CLIENT=postgres
    - DATABASE_HOST=192.168.56.1
    - DATABASE_PORT=54322
    - DATABASE_NAME=strapi
    - DATABASE_USERNAME=techinbrs
    - DATABASE_PASSWORD=54322
  restart: unless-stopped